#!/usr/bin/env python
"""
TODO: Hash the content of the clipbboard, use that hash in default name, and
      check to ensure that that content isn't already dumped to file.
"""
import os
import sys
import argparse
import gtk
import subprocess
from hashlib import sha256
from datetime import datetime

def image_hash(image):
    return sha256(image.get_pixels()).hexdigest()

def parse_arguments(image):
    ihash = image_hash(image)[0:8]
    name = "clipboard-%s-%sx%s.png" % (
        ihash,
        image.props.width,
        image.props.height
    )
    parser = argparse.ArgumentParser(
        description="Write image from clipboard to file"
    )
    parser.add_argument(
        '--name', '-n', type=str, default=name,
        help="Name of the image file"
    )
    parser.add_argument(
        "--open", "-o", action='store_true',
        help="Automatically open the saved image"
    )
    return parser.parse_args()


def main():
    clipboard = gtk.clipboard_get()
    image = clipboard.wait_for_image()
    if image is not None:
        args = parse_arguments(image)
        image.save(args.name, "png")
        print("image saved to %s" % args.name)

        
        if args.open:
            fpath = os.path.abspath(args.name)
            subprocess.call(["/usr/bin/gio", "open", "%s" % fpath])
    else:
        print("no image on clipboard")


if __name__ == '__main__':
    main()